name: Java CI with Gradle

on:
  push:
    branches: [ "main-gradle" ]
  pull_request:
    branches: [ "main-gradle" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: gradle check
